validate-product:
  function: actions/labs/validate-product/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
  limits:
    timeout: 10000
    memorySize: 256
  annotations:
    require-adobe-auth: false
    final: true